o
fC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaDatos\Conexion.csutf-8o
fC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaDatos\DCliente.csutf-8m
dC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaDatos\DCuota.csutf-8p
gC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaDatos\DEmpleado.csutf-8l
cC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaDatos\DPago.csutf-8p
gC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaDatos\DPrestamo.csutf-8r
iC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaDatos\DVentanilla.csutf-8~
uC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaDatos\Properties\AssemblyInfo.csutf-8≠
£C:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaDatos\obj\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.csutf-8≠
£C:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaDatos\obj\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.csutf-8≠
£C:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaDatos\obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.csutf-8r
iC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaEntidades\Cliente.csutf-8p
gC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaEntidades\Cuota.csutf-8s
jC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaEntidades\Empleado.csutf-8o
fC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaEntidades\Pago.csutf-8s
jC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaEntidades\Prestamo.csutf-8Ç
yC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaEntidades\Properties\AssemblyInfo.csutf-8u
lC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaEntidades\Ventanilla.csutf-8±
ßC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaEntidades\obj\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.csutf-8±
ßC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaEntidades\obj\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.csutf-8±
ßC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaEntidades\obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.csutf-8q
hC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaNegocio\NCliente.csutf-8o
fC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaNegocio\NCuota.csutf-8r
iC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaNegocio\NEmpleado.csutf-8n
eC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaNegocio\NPago.csutf-8r
iC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaNegocio\NPrestamo.csutf-8t
kC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaNegocio\NVentanilla.csutf-8Ä
wC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaNegocio\Properties\AssemblyInfo.csutf-8Ø
•C:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaNegocio\obj\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.csutf-8Ø
•C:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaNegocio\obj\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.csutf-8Ø
•C:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaNegocio\obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.csutf-8u
lC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\Program.csutf-8Ö
|C:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\Properties\AssemblyInfo.csutf-8å
ÇC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\Properties\Resources.Designer.csutf-8ã
ÅC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\Properties\Settings.Designer.csutf-8
vC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmLogin.Designer.csutf-8v
mC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmLogin.csutf-8Ü
}C:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmMantClientes.Designer.csutf-8}
tC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmMantClientes.csutf-8á
~C:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmMantEmpleados.Designer.csutf-8~
uC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmMantEmpleados.csutf-8ä
ÄC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmMantVentanillas.Designer.csutf-8Ä
wC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmMantVentanillas.csutf-8~
uC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmMenu.Designer.csutf-8u
lC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmMenu.csutf-8Å
xC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmMenuEmp.Designer.csutf-8x
oC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmMenuEmp.csutf-8Ç
yC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmRegPagos.Designer.csutf-8y
pC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmRegPagos.csutf-8Ü
}C:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmRegPrestamos.Designer.csutf-8}
tC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmRegPrestamos.csutf-8Å
xC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmReporte.Designer.csutf-8x
oC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmReporte.csutf-8à
C:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmReporteCliente.Designer.csutf-8
vC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmReporteCliente.csutf-8ë
áC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmReporteClientePrestamo.Designer.csutf-8á
~C:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmReporteClientePrestamo.csutf-8ä
ÄC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmReporteEmpleado.Designer.csutf-8Ä
wC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmReporteEmpleado.csutf-8å
ÇC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmReporteVentanilla.Designer.csutf-8Ç
yC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\frmReporteVentanilla.csutf-8¥
™C:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\obj\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.csutf-8¥
™C:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\obj\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.csutf-8¥
™C:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\CapaPresentacion\obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.csutf-8}
tC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\UnitTest\Properties\AssemblyInfo.csutf-8o
fC:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\UnitTest\UnitTest1.csutf-8¨
¢C:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\UnitTest\obj\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.csutf-8¨
¢C:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\UnitTest\obj\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.csutf-8¨
¢C:\Users\Alem\Universidad\VIII Ciclo\INSO III\PROYECTO\PROYECTO\DAP_Grupo5-FINAL\UnitTest\obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.csutf-8